import React, { useState, useEffect } from 'react';
import { useParams, Link } from 'react-router-dom';

interface ChatMessage {
  id: string;
  type: 'user' | 'ai';
  content: string;
  timestamp: string;
}

const DocumentView: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [document, setDocument] = useState<any>(null);
  const [chatMessages, setChatMessages] = useState<ChatMessage[]>([]);
  const [newMessage, setNewMessage] = useState('');

  useEffect(() => {
    // TODO: Fetch document by ID from API
    // Mock data for now
    setDocument({
      id: id,
      title: 'Meeting Notes - Jan 15',
      content: `# Meeting Notes - January 15, 2024

## Attendees
- John Smith (PM)
- Sarah Johnson (Dev)
- Mike Chen (Design)

## Key Discussion Points
1. Project timeline review
2. Technical architecture decisions
3. Resource allocation for Q2

## Decisions Made
- Move to microservices architecture
- Implement CI/CD pipeline by March
- Weekly sprint reviews starting next week

## Action Items
- [ ] Sarah: Set up development environment
- [ ] Mike: Create wireframes for new features
- [ ] John: Schedule client review meeting`,
    });

    // Mock chat history
    setChatMessages([
      {
        id: '1',
        type: 'user',
        content: 'What were the key decisions made in this meeting?',
        timestamp: '2024-01-15 14:30',
      },
      {
        id: '2',
        type: 'ai',
        content:
          'Based on your meeting notes, three key decisions were made: 1) Move to microservices architecture, 2) Implement CI/CD pipeline by March, and 3) Start weekly sprint reviews next week.',
        timestamp: '2024-01-15 14:30',
      },
    ]);
  }, [id]);

  const handleSendMessage = () => {
    if (!newMessage.trim()) return;

    // Add user message
    const userMessage: ChatMessage = {
      id: Date.now().toString(),
      type: 'user',
      content: newMessage,
      timestamp: new Date().toLocaleString(),
    };

    setChatMessages((prev) => [...prev, userMessage]);
    setNewMessage('');

    // TODO: Send to AI API and add response
    setTimeout(() => {
      const aiMessage: ChatMessage = {
        id: (Date.now() + 1).toString(),
        type: 'ai',
        content:
          'This is a mock AI response. In the real implementation, this would be generated by analyzing the document content.',
        timestamp: new Date().toLocaleString(),
      };
      setChatMessages((prev) => [...prev, aiMessage]);
    }, 1000);
  };

  if (!document) return <div>Loading...</div>;

  return (
    <div style={{ padding: '20px', maxWidth: '1000px', margin: '0 auto' }}>
      <div style={{ marginBottom: '20px' }}>
        <Link to="/" style={{ textDecoration: 'none' }}>
          ← Back to Dashboard
        </Link>
        <h1 style={{ margin: '10px 0' }}>{document.title}</h1>
      </div>

      <div
        style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '30px' }}
      >
        {/* Document Content */}
        <div>
          <h2>Document Content</h2>
          <div
            style={{
              border: '1px solid #ddd',
              padding: '20px',
              borderRadius: '5px',
              backgroundColor: '#f9f9f9',
              whiteSpace: 'pre-wrap',
              fontFamily: 'monospace',
            }}
          >
            {document.content}
          </div>
        </div>

        {/* Chat Section */}
        <div>
          <h2>Chat about this document</h2>
          <div
            style={{
              border: '1px solid #ddd',
              height: '400px',
              padding: '15px',
              borderRadius: '5px',
              overflowY: 'auto',
              marginBottom: '15px',
            }}
          >
            {chatMessages.map((msg) => (
              <div
                key={msg.id}
                style={{
                  marginBottom: '15px',
                  padding: '10px',
                  borderRadius: '5px',
                  backgroundColor: msg.type === 'user' ? '#e3f2fd' : '#f5f5f5',
                }}
              >
                <div style={{ fontWeight: 'bold', marginBottom: '5px' }}>
                  {msg.type === 'user' ? '💬 You' : '🤖 AI'}
                </div>
                <div>{msg.content}</div>
                <small style={{ color: '#666' }}>{msg.timestamp}</small>
              </div>
            ))}
          </div>

          <div style={{ display: 'flex', gap: '10px' }}>
            <input
              type="text"
              value={newMessage}
              onChange={(e) => setNewMessage(e.target.value)}
              onKeyPress={(e) => e.key === 'Enter' && handleSendMessage()}
              placeholder="Ask a question about this document..."
              style={{ flex: 1, padding: '10px' }}
            />
            <button
              onClick={handleSendMessage}
              style={{ padding: '10px 20px' }}
            >
              Send
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DocumentView;
